AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Hello World
# Metadata: 

# Parameters: 

# Mappings: 

# Conditions: 

Resources: 
  CreatePipelineLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub [
          "create-pipeline-lambda-${ID}",
          ID: !Select [2, !Split ["/", !Ref AWS::StackId]],
        ] # Append the stack UUID
      CodeUri: src/create-pipeline
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 100
      # Policies:
      #   - EventBridgePutEventsPolicy:
      #       EventBusName: !Ref EventBusName
      #   - Version: "2012-10-17"
      #     Statement:
      #       - Effect: Allow
      #         Action:
      #           - secretsmanager:DescribeSecret
      #           - secretsmanager:GetSecretValue
      #         Resource: !Ref WebhookSecretsManager
  GithubHandlerLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub [
          "github-handler-lambda-${ID}",
          ID: !Select [2, !Split ["/", !Ref AWS::StackId]],
        ] # Append the stack UUID
      CodeUri: src/github-handler
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 100
  UpdateGithubBuildStatusLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub [
          "update-build-lambda-${ID}",
          ID: !Select [2, !Split ["/", !Ref AWS::StackId]],
        ] # Append the stack UUID
      CodeUri: src/github-handler
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 100
