name: Deploy Serverless Function

on:
  push:
    branches: [main]
env:
  BUCKET_NAME: ${{ vars.SAM_BUCKET_NAME }}
  STACK_NAME: bwc-infra-lambda-func
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: AWS Version
        run: aws --version

      - name: Create S3 Bucket
        run: sh create-s3.sh
      

      - name: Validate and Deploy AWS Serverless Functions
        run: |
          aws cloudformation validate-template --template-body file://template.yaml
          aws cloudformation package  --template-file template.yaml --s3-bucket ${BUCKET_NAME} --s3-prefix bwc-infra --output-template-file template-package.yaml
          aws cloudformation deploy --template-file template-package.yaml --stack-name ${STACK_NAME}
